#!/usr/bin/env python
import os
import sys
import subprocess
import shutil

def main():
    print("=========================================")
    print("      NovaLang Release Build System      ")
    print("=========================================")
    
    # 1. Clean previous build artifacts
    print("\n[1/4] Cleaning previous builds...")
    folders_to_clean = ["build", "dist", "novalang.egg-info"]
    for folder in folders_to_clean:
        if os.path.exists(folder):
            print(f"Removing '{folder}'...")
            shutil.rmtree(folder)
            
    # 2. Build Python Package (Wheel & Source Dist)
    print("\n[2/4] Building Python Package (.whl & .tar.gz)...")
    try:
        # Check if build tool is installed
        import build
    except ImportError:
        print("Installing 'build' package...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", "build"])
        
    try:
        subprocess.check_call([sys.executable, "-m", "build"])
        print("Python packages generated successfully in 'dist/'!")
    except Exception as e:
        print(f"Error building Python packages: {e}")
        
    # 3. Build Standalone Executable (via PyInstaller)
    print("\n[3/4] Checking PyInstaller for standalone binary build...")
    pyinstaller_installed = False
    try:
        subprocess.check_output(["pyinstaller", "--version"], stderr=subprocess.STDOUT)
        pyinstaller_installed = True
    except (FileNotFoundError, subprocess.CalledProcessError):
        # Check if installed in python env but not on system PATH
        try:
            subprocess.check_output([sys.executable, "-m", "PyInstaller", "--version"], stderr=subprocess.STDOUT)
            pyinstaller_installed = True
        except Exception:
            pass
            
    if pyinstaller_installed:
        print("PyInstaller detected! Building standalone binary...")
        try:
            # We bundle novalang/main.py as a single executable file named 'nova'
            cmd = [
                sys.executable, "-m", "PyInstaller",
                "--onefile",
                "--name", "nova",
                "--collect-submodules", "novalang",
                "novalang/main.py"
            ]
            subprocess.check_call(cmd)
            print("\nStandalone binary built successfully in 'dist/'!")
            if os.name == 'nt':
                print("Output: dist/nova.exe")
            else:
                print("Output: dist/nova")
        except Exception as e:
            print(f"Failed to build standalone binary: {e}")
    else:
        print("PyInstaller not found. Skipping standalone binary generation.")
        print("To build a standalone binary, run:")
        print("  pip install pyinstaller")
        print("  python build_release.py")
        
    # 4. Cleanup temporary setup directories
    print("\n[4/4] Cleaning temporary compilation files...")
    temp_folders = ["build", "novalang.egg-info"]
    for folder in temp_folders:
        if os.path.exists(folder):
            shutil.rmtree(folder)
            
    # Remove spec file generated by PyInstaller
    if os.path.exists("nova.spec"):
        os.remove("nova.spec")
        
    print("\n=========================================")
    print("Build complete! Check the 'dist/' directory.")
    print("=========================================")

if __name__ == "__main__":
    main()
